# Generated by cpp11: do not edit by hand

C_murphydiag_prob <- function(x, y) {
  .Call(`_triptych_C_murphydiag_prob`, x, y)
}

C_murphydiag_prob_ref <- function(x, y, ref) {
  .Call(`_triptych_C_murphydiag_prob_ref`, x, y, ref)
}

C_murphydiag_mean <- function(x, y) {
  .Call(`_triptych_C_murphydiag_mean`, x, y)
}

C_murphydiag_mean_ref <- function(x, y, ref) {
  .Call(`_triptych_C_murphydiag_mean_ref`, x, y, ref)
}

C_murphydiag_median <- function(x, y) {
  .Call(`_triptych_C_murphydiag_median`, x, y)
}

C_murphydiag_median_ref <- function(x, y, ref) {
  .Call(`_triptych_C_murphydiag_median_ref`, x, y, ref)
}

C_murphydiag_quant <- function(x, y, level) {
  .Call(`_triptych_C_murphydiag_quant`, x, y, level)
}

C_murphydiag_quant_ref <- function(x, y, level, ref) {
  .Call(`_triptych_C_murphydiag_quant_ref`, x, y, level, ref)
}

C_murphydiag_expect <- function(x, y, level) {
  .Call(`_triptych_C_murphydiag_expect`, x, y, level)
}

C_murphydiag_expect_ref <- function(x, y, level, ref) {
  .Call(`_triptych_C_murphydiag_expect_ref`, x, y, level, ref)
}
